name: Deploy

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        uses: marshallku/gifconverter/.github/workflows/build.yml@master
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: ["build"]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: gifconverter-artifact
                  path: dist/
            - name: Deploy via SCP
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.ED_KEY }}
                  source: "dist"
                  target: "/var/www"
            - name: Run shell script
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.ED_KEY }}
                  script_stop: true
                  script: |
                      cd /var/www
                      ./deploy.sh gifconverter
